# Generated by Django 5.1.3 on 2024-12-16 12:01

import music_controller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=music_controller.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
